### ISSUE TITLE
Compasion to NLPScholar using title + abstract

### ISSUE THREAD

**Issue by jpwahle** [gipplab/cs-insights-crawler#48]
**Description of the Epic's Goal**
The goal of this epic has two parts:

* to compare our analysis using titles and abstracts to NLPScholar using Titles only.
* formulate this as an interesting research question. What do abstracts provide additionally over only titles?
* which questions can we now answer that were not possible without abstracts?
* how can we categorize abstracts?

**Issues to resolve the Epic**

- [ ] Title Unigrams
- [ ] Title Bigrams
- [ ] Abstracts Unigrams
- [ ] Abstracts Bigrams
- [ ] Title+Abstract Unigrams - tf-idf?
- [ ] Title+Abstract Bigrams - tf-idf?
- [ ] LDA between NLPS and NLPS2 over time
